# Generated by Django 5.1.1 on 2024-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Address'),
        ),
    ]
